name: Test Google Sheet Connection

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"   # 9 AM IST daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test import moviepy
      run: |
        pip install moviepy
        python - <<EOF
import moviepy
import moviepy.editor as mp
print("MoviePy imported successfully!")
EOF
